import path from 'node:path';
import { realpath } from 'node:fs/promises';
import { MCP_FILE, MCP_SERVER_NAME, isObject, readContained } from './common.js';
import { makeUnifiedDiff } from './diff.js';
import { git } from './ignore.js';
import { createPlan } from './plan.js';
import { canonicalJson, parseExpect, sha256 } from './pin.js';

// Compatible upgrades use adoption's rendered-byte checks and preconditions.
// No migration of generated files or authority is performed here.
export async function createUpgradePlan({ root: rootArgument, adapter }) {
  const plan = {
    planFormat: 'dev-foundry.upgrade-plan.v1', mode: 'upgrade', status: 'blocked',
    current: null, target: adapter, repository: null, activation: null,
    create: [], merge: [], delete: [], noop: [], blockers: [], preconditions: {},
  };
  const ops = { writes: [], deletes: [] };
  const finish = () => {
    const bytes = Buffer.from(canonicalJson(plan));
    return { plan, bytes, hash: sha256(bytes), ops };
  };
  const block = (code, message) => plan.blockers.push({ code, message });
  let root, before, config, entry;
  try {
    root = await realpath(path.resolve(rootArgument ?? process.cwd()));
    before = await readContained(root, MCP_FILE);
    config = JSON.parse(before.toString('utf8'));
    entry = config.mcpServers[MCP_SERVER_NAME];
    if (!isObject(entry) || entry.command !== 'dev-foundry-claude' ||
        !Array.isArray(entry.args) || entry.args[0] !== 'mcp' || entry.args[1] !== '--expect') throw new Error();
    const pin = parseExpect(entry.args[2]);
    plan.current = { version: pin.version, payloadRoot: pin.root, expect: entry.args[2] };
  } catch {
    block('upgrade-current-pin-invalid', 'A valid existing adapter runtime pin is required.');
    return finish();
  }

  // Rendering differs only in the MCP pin. Check against the current pin to
  // inspect every other target-generated byte through the adoption model.
  const compatible = await createPlan({ root, adapter: plan.current });
  plan.activation = compatible.plan.activation;
  plan.preconditions = compatible.plan.preconditions;
  plan.guaranteed_untouched = compatible.plan.guaranteed_untouched;
  const head = git(root, ['rev-parse', 'HEAD']);
  const drift = git(root, ['diff', 'HEAD', '--binary']);
  const status = git(root, ['status', '--porcelain', '--untracked-files=all']);
  if (head.status !== 0 || drift.status !== 0 || status.status !== 0) {
    block('upgrade-repository-invalid', 'Repository state cannot be established.');
  }
  plan.repository = { root, head: head.stdout.trim(), diffSha256: sha256(drift.stdout), statusSha256: sha256(status.stdout) };
  if (compatible.plan.status !== 'noop') {
    plan.blockers.push(...compatible.plan.blockers);
    block('upgrade-migration-required', 'The adapter-owned surface is not byte-compatible with the target; a separately governed migration is required.');
  }
  if (plan.blockers.length) return finish();
  if (plan.current.expect === adapter.expect) {
    plan.status = 'noop';
    plan.noop = [MCP_FILE];
    return finish();
  }
  const touched = git(root, ['status', '--porcelain', '--untracked-files=all', '--', MCP_FILE]);
  if (touched.status !== 0 || touched.stdout.trim() !== '') {
    block('dirty-working-tree', 'The runtime pin path has uncommitted changes.');
    return finish();
  }
  entry.args[2] = adapter.expect;
  const after = `${JSON.stringify(config, null, 2)}\n`;
  plan.merge = [{ path: MCP_FILE, before_sha256: sha256(before), after_sha256: sha256(after), diff: makeUnifiedDiff(MCP_FILE, before.toString('utf8'), after) }];
  ops.writes.push({ path: MCP_FILE, content: after });
  plan.status = 'ready';
  return finish();
}

export async function upgradeStatus(options) {
  const { plan } = await createUpgradePlan(options);
  return { status: plan.status === 'noop' ? 'current' : plan.status === 'ready' ? 'upgrade-needed' : 'blocked',
    current: plan.current, target: plan.target, blockers: plan.blockers };
}
