import { canonicalJson, sha256 } from '../adopt/pin.js';
import { refuse } from './identity.js';

export function approvedFields(plan, hash) {
  return { planSha256: hash, project: plan.project, sourceAuthority: plan.sourceAuthority,
    sourcePin: plan.sourcePin, targetPin: plan.targetPin, branch: plan.repository.branch,
    head: plan.repository.head, choices: plan.choices, paths: plan.files.map(f => f.path),
    sourceSessionId: plan.proposal.sourceSessionId };
}

// Approval and gate dispositions are trusted caller data, not proof generated by
// this module. Evidence bytes are reobserved independently at each boundary.
export function authorize(plan, hash, approval, evidence, now = Date.now()) {
  if (sha256(canonicalJson(plan)) !== hash || plan.format !== 'dev-foundry.runtime-plan.v1') refuse('wrong-plan-hash');
  if (approval?.format !== 'dev-foundry.runtime-approval.v1' || approval.operator !== plan.operator ||
      approval.operatorApproved !== true || approval.sourceAuthorized !== true ||
      !Number.isSafeInteger(approval.expiresAt) || approval.expiresAt <= now ||
      canonicalJson(approval.bound) !== canonicalJson(approvedFields(plan, hash)) ||
      canonicalJson(approval.phases) !== canonicalJson(['prepare', 'commit'])) refuse('approval-invalid-or-stale');
  if (!Array.isArray(evidence) || evidence.length !== plan.gates.length) refuse('gates-unsatisfied');
  for (const gate of plan.gates) {
    const match = evidence.filter(e => e.id === gate.id);
    if (match.length !== 1 || match[0].status !== 'PASS' || match[0].sha256 !== gate.sha256) refuse('gates-unsatisfied');
  }
  return structuredClone(approval);
}
